services:
  tests:
    image: python:3.12.0a4-alpine3.17
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/workspace
    command: /bin/sh -c "pytest --asyncio-mode=auto  --alluredir=allure-results -vs -n 4"
    working_dir: /usr/workspace
