services:
  tests:
    image: python:3.12-bookworm
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/workspace
    command: /bin/sh -c "pytest -n 4 --asyncio-mode=auto  --alluredir=allure-results -vs"
    working_dir: /usr/workspace
